export default {
  api:{
    getContactList:{
      url:"/contactList",
      method:"get"
    },
    delContactById:{
      url:"/contact",
      method:"delete"
    },
    updateContact:{
      url:"/contact/edit",
      method:"put"
    },
    createContactByForm:{
      url:"/contact/new/form",
      method:"post",
      isForm:true
    },
    createContactByJosn:{
      url:"/contact/new/json",
      method:"post"
    }
  },
  baseUrl:"http://localhost:9000/api",
  timeout:5000,
  name:"contact"
}
